name: Build
on:
  push:
    branches:
      - main
      - devel
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - devel
jobs:
  build:
    name: ${{ matrix.os-name }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        include:
          - os: windows-latest
            os-name: Windows
          - os: ubuntu-latest
            os-name: Ubuntu
          - os: macos-latest
            os-name: macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment for C / C++
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
      - name: Pull dependencies
        run: |
          cargo fetch
      - name: Build debug
        run: |
          cargo build
      - name: Build release
        run: |
          cargo build --release
      - name: Run tests on debug
        run: |
          cargo test
