name: Run Miri
on:
  push:
    branches:
      - main
      - devel
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - devel
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build and invoke Miri (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull dependencies
        run: |
          cargo fetch
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Run Miri
        run: |
          cargo miri test
